import 'package:flutter/foundation.dart';

class AppLocalizations {
  static final ValueNotifier<String> currentLocale = ValueNotifier<String>('en');

  static const _localizedValues = {
    'en': {
      'app_title': 'HERO-IE',
      'app_tagline': 'Hospitality Emergency Response',
      'role_selection': 'Select your role to connect to the venue safety mesh.',
      'connect_guest': 'Connect as Guest (User)',
      'connect_staff': 'Connect as Staff (Admin)',
      'guest_dashboard': 'Guest Dashboard',
      'admin_dashboard': 'Staff Command Center',
      'sos_button': 'SOS / TRIGGER ALARM',
      'sos_chat': 'Emergency Chat',
      'broadcast': 'Broadcast',
      'live_camera': 'Live Camera Feed',
      'facility_layout': 'Facility Layout',
      'safe_path': 'Evacuation Route:',
      'status_connected': 'CONNECTED',
      'status_offline': 'OFFLINE',
      'no_emergency': 'No active emergency. Stay safe.',
      'safe_path_calculated': 'Dynamic Safe Path Calculated!',
      'connectivity_error': 'Connectivity error. Using local mesh...',
      'sos_activated_msg': 'SOS Activated. Follow safe path.',
      'uploading_ai': 'Uploading media to AI...',
      'ai_analysis_received': 'AI Analysis Received!',
      'upload_failed': 'Upload failed. Using mesh fallback.',
      'describe_emergency': 'Describe emergency...',
      'send_sos': 'SEND SECURE SOS',
      'broadcast_alerts': 'BROADCAST ALERTS',
      'broadcast_hint': 'Enter emergency instruction to push to all meshes...',
      'heatmap_title': 'Live Risk Heatmap',
      'preparing_sim': 'PREPARING SIMULATION...',
      'no_stream': 'NO LIVE STREAM CONNECTED',
      'live_polling': 'LIVE: POLLING...',
      'start_sim_btn': 'START LIVE SIMULATION',
      'sim_ready_msg': 'LIVE FEED READY: Poll requests optimized.',
      'sim_stopped_msg': 'LIVE FEED STOPPED',
      'configure_layout': 'Configure Facility Layout',
      'layout_hint': 'Describe layout details/hazards...',
      'upload_floorplan': 'Upload Floorplan Image',
      'close_btn': 'CLOSE',
      'cancel_btn': 'CANCEL',
      'sim_dialog_title': 'Live Camera Simulation',
      'sim_dialog_body': 'Connect to the 5s AI ingestion cycle. Select a video to simulate a live stream.',
    },
    'hi': {
      'app_title': 'हीरो-आईई',
      'app_tagline': 'आतिथ्य आपातकालीन प्रतिक्रिया',
      'role_selection': 'सुरक्षा जाल से जुड़ने के लिए अपनी भूमिका चुनें।',
      'connect_guest': 'अतिथि के रूप में जुड़ें',
      'connect_staff': 'कर्मचारी के रूप में जुड़ें',
      'guest_dashboard': 'अतिथि डैशबोर्ड',
      'admin_dashboard': 'कर्मचारी नियंत्रण कक्ष',
      'sos_button': 'आपातकालीन अलार्म',
      'sos_chat': 'आपातकालीन चैट',
      'broadcast': 'प्रसारण',
      'live_camera': 'लाइव कैमरा फ़ीड',
      'facility_layout': 'सुविधा लेआउट',
      'safe_path': 'निकासी मार्ग:',
      'status_connected': 'जुड़ा हुआ',
      'status_offline': 'ऑफलाइन',
      'no_emergency': 'कोई आपात स्थिति नहीं। सुरक्षित रहें।',
      'safe_path_calculated': 'सुरक्षित मार्ग की गणना की गई!',
      'connectivity_error': 'कनेक्टिविटी त्रुटि। स्थानीय मेश का उपयोग कर रहे हैं...',
      'sos_activated_msg': 'आपातकालीन मोड सक्रिय। सुरक्षित मार्ग का पालन करें।',
      'uploading_ai': 'एआई को मीडिया अपलोड किया जा रहा है...',
      'ai_analysis_received': 'एआई विश्लेषण प्राप्त हुआ!',
      'upload_failed': 'अपलोड विफल। मेश का उपयोग कर रहे हैं।',
      'describe_emergency': 'आपातकाल का वर्णन करें...',
      'send_sos': 'सुरक्षित एसओएस भेजें',
      'broadcast_alerts': 'अलर्ट प्रसारित करें',
      'broadcast_hint': 'सभी मेश पर भेजने के लिए निर्देश लिखें...',
      'heatmap_title': 'लाइव जोखिम हीटमैप',
      'preparing_sim': 'सिमुलेशन की तैयारी...',
      'no_stream': 'कोई लाइव स्ट्रीम कनेक्ट नहीं है',
      'live_polling': 'लाइव: डेटा प्राप्त हो रहा है...',
      'start_sim_btn': 'सिमुलेशन शुरू करें',
      'sim_ready_msg': 'लाइव फीड तैयार।',
      'sim_stopped_msg': 'लाइव फीड बंद हो गई',
      'configure_layout': 'सुविधा लेआउट कॉन्फ़िगर करें',
      'layout_hint': 'लेआउट विवरण लिखें...',
      'upload_floorplan': 'फ्लोरप्लान अपलोड करें',
      'close_btn': 'बंद करें',
      'cancel_btn': 'रद्द करें',
      'sim_dialog_title': 'लाइव कैमरा सिमुलेशन',
      'sim_dialog_body': 'एआई चक्र से जुड़ें। वीडियो चुनें।',
    },
    'mr': {
      'app_title': 'हिरो-आयई',
      'app_tagline': 'आतिथ्य आणीबाणी प्रतिसाद',
      'role_selection': 'सुरक्षा जाळ्याशी जोडण्यासाठी तुमची भूमिका निवडा.',
      'connect_guest': 'अतिथी म्हणून जोडा',
      'connect_staff': 'कर्मचारी म्हणून जोडा',
      'guest_dashboard': 'अतिथी डॅशबोर्ड',
      'admin_dashboard': 'कर्मचारी नियंत्रण कक्ष',
      'sos_button': 'त्वरित मदत (SOS)',
      'sos_chat': 'आणीबाणी चॅट',
      'broadcast': 'प्रसारण',
      'live_camera': 'थेट कॅमेरा',
      'facility_layout': 'सुविधा लेआउट',
      'safe_path': 'सुरक्षित मार्ग:',
      'status_connected': 'कनेक्टेड',
      'status_offline': 'ऑफलाइन',
      'no_emergency': 'आणीबाणी नाही. सुरक्षित रहा.',
      'safe_path_calculated': 'सुरक्षित मार्ग सापडला!',
      'connectivity_error': 'नेटवर्क त्रुटी. लोकल मेश वापरत आहे...',
      'sos_activated_msg': 'SOS सक्रिय. सुरक्षित मार्गाचे अनुसरण करा.',
      'uploading_ai': 'AI ला मीडिया पाठवत आहे...',
      'ai_analysis_received': 'AI विश्लेषण मिळाले!',
      'upload_failed': 'अपलोड अयशस्वी.',
      'describe_emergency': 'आणीबाणीचे वर्णन करा...',
      'send_sos': 'सुरक्षित SOS पाठवा',
      'broadcast_alerts': 'अलर्ट पाठवा',
      'broadcast_hint': 'इशारा संदेश लिहा...',
      'heatmap_title': 'थेट जोखीम नकाशा',
      'preparing_sim': 'तयारी सुरू आहे...',
      'no_stream': 'थेट प्रवाह नाही',
      'live_polling': 'थेट: डेटा येत आहे...',
      'start_sim_btn': 'सुरू करा',
      'sim_ready_msg': 'थेट फीड तयार.',
      'sim_stopped_msg': 'थेट फीड थांबवले',
      'configure_layout': 'लेआउट सेट करा',
      'layout_hint': 'तपशील लिहा...',
      'upload_floorplan': 'नकाशा अपलोड करा',
      'close_btn': 'बंद करा',
      'cancel_btn': 'रद्द करा',
      'sim_dialog_title': 'कॅमेरा सिमुलेशन',
      'sim_dialog_body': 'व्हिडिओ निवडा आणि सुरू करा.',
    },
    'bn': {
      'app_title': 'হিরো-আইই',
      'app_tagline': 'হসপিটালিটি ইমারজেন্সি রেসপন্স',
      'role_selection': 'সুরক্ষা জালে যুক্ত হতে আপনার ভূমিকা চয়ন করুন।',
      'connect_guest': 'গেস্ট হিসেবে যুক্ত হন',
      'connect_staff': 'স্টাফ হিসেবে যুক্ত হন',
      'guest_dashboard': 'গেস্ট ড্যাশবোর্ড',
      'admin_dashboard': 'স্টাফ কমান্ড সেন্টার',
      'sos_button': 'জরুরী অ্যালার্ম (SOS)',
      'sos_chat': 'জরুরী চ্যাট',
      'broadcast': 'সম্প্রচার',
      'live_camera': 'লাইভ ক্যামেরা',
      'facility_layout': 'ফ্যাসিলিটি লেআউট',
      'safe_path': 'নিরাপদ পথ:',
      'status_connected': 'সংযুক্ত',
      'status_offline': 'অফলাইন',
      'no_emergency': 'কোনও জরুরী অবস্থা নেই। নিরাপদ থাকুন।',
      'safe_path_calculated': 'নিরাপদ পথ গণনা করা হয়েছে!',
      'connectivity_error': 'সংযোগ ত্রুটি। লোকাল মেশ ব্যবহার করা হচ্ছে...',
      'sos_activated_msg': 'জরুরী অবস্থা সক্রিয়। নিরাপদ পথ অনুসরণ করুন।',
      'uploading_ai': 'এআই তে মিডিয়া আপলোড হচ্ছে...',
      'ai_analysis_received': 'এআই বিশ্লেষণ প্রাপ্ত হয়েছে!',
      'upload_failed': 'আপলোড ব্যর্থ হয়েছে।',
      'describe_emergency': 'জরুরী অবস্থার বিবরণ দিন...',
      'send_sos': 'সুরক্ষিত এসওএস পাঠান',
      'broadcast_alerts': 'সতর্কবার্তা সম্প্রচার করুন',
      'broadcast_hint': 'নির্দেশাবলী লিখুন...',
      'heatmap_title': 'লাইভ রিস্ক হিটম্যাপ',
      'preparing_sim': 'সিমুলেশন প্রস্তুত হচ্ছে...',
      'no_stream': 'কোনও লাইভ স্ট্রিম নেই',
      'live_polling': 'লাইভ: ডেটা আসছে...',
      'start_sim_btn': 'সিমুলেশন শুরু করুন',
      'sim_ready_msg': 'লাইভ ফিড প্রস্তুত।',
      'sim_stopped_msg': 'লাইভ ফিড বন্ধ হয়েছে',
      'configure_layout': 'লেআউট কনফিগার করুন',
      'layout_hint': 'বিবরণ লিখুন...',
      'upload_floorplan': 'ফ্লোরপ্ল্যান আপলোড করুন',
      'close_btn': 'বন্ধ করুন',
      'cancel_btn': 'বাতিল করুন',
      'sim_dialog_title': 'লাইভ ক্যামেরা সিমুলেশন',
      'sim_dialog_body': 'ভিডিও নির্বাচন করে শুরু করুন।',
    }
  };

  static String translate(String key) {
    return _localizedValues[currentLocale.value]?[key] ?? _localizedValues['en']?[key] ?? key;
  }
}
